### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by freesolo92** [ros-planning/moveit_calibration#102]
Hi,

every time i try to build the package, I get the following build error about OpenCV:

```
Errors     << moveit_calibration_plugins:cmake /home/jetson/test_ws/logs/moveit_calibration_plugins/build.cmake.009.log                                                
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenCV (missing: aruco) (found suitable version "4.1.1",
  minimum required is "4.1.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/lib/aarch64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake:328 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)
```

Does anyone know how to deal with it? Are there any adaption steps in the CMake file I have to do?

I build the package with `catkin build moveit_calibration_plugins` and I use ROS Meldodic on Ubuntu 18 on a ARM Device.

Thanks for any hint.

**Comment by ericahellscythe** [comment]
Hi @freesolo92 I know this is closed and a year ago but did you manage to resolve this issue? If so please share it with me, I'm also facing this issue now.
