### ISSUE TITLE
Reprojection Error

### ISSUE THREAD

**Issue by rakkidi** [ros-planning/moveit_calibration#105]
Hello!
I have been using this package recently to calibrate a RealSense D435 to a FE Panda arm.

The result of the reprojection error varies and is between 0.015m to 0.02m.
I have tried several calibrations with different poses/rotation and sample size, but I am not able to get below those values.

**Question**
Are these values good and if not, do you think the reason for it is the camera or the taken samples?

**Comment by nadavmoran1** [comment]
Hey,
I also used this package to calibrate my RealSense D435 to a Xarm 6 DOF arm.
I printed a 5x7 target that the package generated and took 70 samples, but the results were quite bad.

The reprojection error was about 0.02m and 0.01r, which turned to be far then what I needed.
From what I heard that calibration should give a reprojection error 10 times smaller and surely this is not the case.

Do you have any idea what I did wrong? I made sure the target was flat and I entered the correct marker and separation sizes.

Thanks in advance,
Nadav
