### ISSUE TITLE
I cannot complete the calibration process.

### ISSUE THREAD

**Issue by OTT123** [ros-planning/moveit_calibration#138]
I've set everything up in the graphical interface. And start taking samples manually. When I take the fifth sample, I get the error: 
`Error:Failed to load python module: handeye.calibrator` 
Is there something wrong with the sampling I took, or is there something wrong with my python environment?
![image](https://github.com/ros-planning/moveit_calibration/assets/99379651/81f45f9c-b6f3-41ab-bfd7-38f4439a254c)

**Comment by OTT123** [comment]
ubuntu 20.04; ros-noetic;

**Comment by LiJihao138** [comment]
I have the same problem. How can you fix it?

**Comment by Akumar201** [comment]
Hello, I am facing the same issue , can you please tell me how did you fixed it ? 

![Image](https://github.com/user-attachments/assets/f805f007-3e30-4fae-bd7f-5eabdf8c4366)
