### ISSUE TITLE
Moveit_Calibration Compile Issue

### ISSUE THREAD

**Issue by JialingTong** [ros-planning/moveit_calibration#23]
Hi Moveit_Calibration Team,

I am trying to use moveit_calibration to achieve the hand-eye calibration, but meet some issue during the compilation.

I used `catkin build` to compile this ROS package in ROS melodic. It shows me the following error:
error: ‘class rviz_visual_tools::TFVisualTools’ has no member named ‘clearAllTransforms’; did you mean ‘publishAllTransforms’?
error: no matching function for call to ‘moveit_visual_tools::MoveItVisualTools::publishMesh(Eigen::Isometry3d&, shape_msgs::Mesh&, rviz_visual_tools::colors, double, const char [4], int)’

Are there any solutions for these two error? Besides, can this package work on ROS kinetic?

Thank you so much!

**Comment by JStech** [comment]
`clearAllTransforms` is in the [master branch of `rviz_visual_tools`](https://github.com/PickNikRobotics/rviz_visual_tools/). Similarly for `publishMesh` and [`moveit_visual_tools`](https://github.com/ros-planning/moveit_visual_tools). If you add those repos to your workspace it'll build.

I've only used melodic. The ArUco module in OpenCV was buggy before 3.4 (melodic/xenial are on 3.2), so I wouldn't have high expectations for kinetic.

**Comment by JialingTong** [comment]
Thank you! I will have a try!

**Comment by neerja123-gupta** [comment]
Hello, I was also facing the same issue. However, when I tried adding  master branch of rviz_visual_tools and moveit_visual_tools to the workspace, I faced a new error: ‘moveit_msgs::DisplayRobotState  has no member named ‘hide’. Any idea about this error. Thank you very much!

**Comment by neerja123-gupta** [comment]
@JStech I tried your suggestion of adding master branch of rviz_visual_tools and  moveit_visual_tools, but I am still facing the same error. Any idea how to resolve this. Thank you very much!

**Comment by JStech** [comment]
@neerja123-gupta, did you rebuild? Maybe try to clean and rebuild?

**Comment by neerja123-gupta** [comment]
Yeah, I cleaned it and tried to rebuild it but its still the same. The error is " error: ‘class rviz_visual_tools::TFVisualTools’ has no member named ‘clearAllTransforms’; did you mean ‘publishAllTransforms’?
     tf_tools_->clearAllTransforms();
"

**Comment by JStech** [comment]
Hmm. It's definitely [in the source code](https://github.com/PickNikRobotics/rviz_visual_tools/blob/9454ac5e51dddf0fd3a582d90377e846819a5a52/include/rviz_visual_tools/tf_visual_tools.h#L81). It seems to me the most likely explanation is that your build isn't finding it and is using the system-installed package.

**Comment by neerja123-gupta** [comment]
Yes, you were right it was using the system installed package. So. I delete them and then added master branch of rviz_visual_tools and moveit_visual_tools to my workspace and it worked. Thank you very much!

**Comment by samarth-robo** [comment]
@JStech I'm on `melodic`. Building the master branch of `moveit_visual_tools` in turn gave me errors related to `geometric_shapes` and `moveit_msgs`. But if I removed the system-wide versions of those two packages, they would get re-installed in the `rosdep install` step for `moveit_visual_tools`. So in the end I used [workspace overlaying](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying): created a separate workspace containing just the master branches of `geometric_shapes` and `moveit_msgs`, sourced that workspace, and then built the workspace containing `moveit_visual_tools`, `rviz_visual_tools`, and `moveit_calibration`.

**Comment by felixvd** [comment]
You could also have cloned the packages into your workspaces and built them from source, but workspace overlaying is great for heavy packages like moveit.

**Comment by samarth-robo** [comment]
> @JStech I'm on `melodic`. Building the master branch of `moveit_visual_tools` in turn gave me errors related to `geometric_shapes` and `moveit_msgs`. But if I removed the system-wide versions of those two packages, they would get re-installed in the `rosdep install` step for `moveit_visual_tools`. So in the end I used [workspace overlaying](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying): created a separate workspace containing just the master branches of `geometric_shapes` and `moveit_msgs`, sourced that workspace, and then built the workspace containing `moveit_visual_tools`, `rviz_visual_tools`, and `moveit_calibration`.

Hmm it seems like something in `move_group` that comes from installing MoveIt from binary packages for `melodic` is not compatible with the `master` branch of `moveit_visual_tools`. In the end, [installing MoveIt from source](https://moveit.ros.org/install/source/) made everything work.

**Comment by fbottarel** [comment]
@samarth-robo I am facing your same problem, and I'm trying to resort to your same solution. Did you end up removing MoveIt from your system via `apt-get remove` or `purge` and then re-install it from source? I might need to do the same but I'm quite hesitant since that would basically remove my ROS installation (I installed from binaries, `ros-melodic-desktop-full`).

**Comment by felixvd** [comment]
You don't need to remove any ROS packages you installed as binaries. ROS workspaces are [layered](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying), so packages you compile in your workspace (the overlay) take precedence over the installed binaries (the underlay). You can just clone MoveIt into your workspace and build it.

**Comment by JStech** [comment]
Since the recent Noetic releases, I think the `master` branches of some of these repos are no longer compatible with Melodic. I'm doing a fresh build in a Docker container to make sure I catch everything (which is still running), but I think the following repos should be switched to `melodic-devel`:

- `geometric_shapes`
- `moveit`
- `moveit_visual_tools`

**Comment by Victorlouisdg** [comment]
Hi

I'm having the same build issue. I'm also on Melodic. I tried cloning these repos into the `src` folder of my workspace:

```
git clone https://github.com/PickNikRobotics/rviz_visual_tools.git -b melodic-devel
git clone https://github.com/ros-planning/moveit_visual_tools.git -b melodic-devel
git clone https://github.com/ros-planning/geometric_shapes.git -b melodic-devel
```

and then building with `catkin_make`, but I'm still getting this error:
```error: ‘class rviz_visual_tools::TFVisualTools’ has no member named ‘clearAllTransforms’```

Did I miss anything?

**Comment by JStech** [comment]
`rviz_visual_tools` should be on `master`. The three repos that need to use `melodic-devel` are listed in my previous comment.

**Comment by ScottYang1982** [comment]
@JialingTong ,
   So it works on kinetic or not? thanks.

**Comment by Victorlouisdg** [comment]
Thanks for the clarification @JStech ! That fixed the build issue :)

**Comment by huangjiancong1** [comment]
> `clearAllTransforms` is in the [master branch of `rviz_visual_tools`](https://github.com/PickNikRobotics/rviz_visual_tools/). Similarly for `publishMesh` and [`moveit_visual_tools`](https://github.com/ros-planning/moveit_visual_tools). If you add those repos to your workspace it'll build.
> 
> I've only used melodic. The ArUco module in OpenCV was buggy before 3.4 (melodic/bionic are on 3.2), so I wouldn't have high expectations for kinetic.

This work!! Thanks @JStech

**Comment by shabelson** [comment]
Thanks! Helped a lot!
(ros-melodic ubuntu 18.04)
cloned:
`rviz_visual_tools `(master)
`moveit_visual_tools` (melodic-devel)
to the same workspace as` moveit_calibration`
