### ISSUE TITLE
I cannot fill "Object frame" field in "Context" tab

### ISSUE THREAD

**Issue by victor-robotic-24** [ros-planning/moveit_calibration#27]
I launch RViz environment and I add the new panel "HandEyeCalibration". I can create succesfully the target in the first tab ("Target"), but when I access to the second tab ("Context"), I cannot fill "Object frame" field which appears empty (without any option to select).

**Comment by JStech** [comment]
I'm guessing you figured this out, since you closed the issue. I'll reply in case someone else runs into the same issue again.

The most likely cause for this is that the target isn't visible to the camera, so the target frame hasn't yet been published.
