### ISSUE TITLE
Is there a minimal robot's DOF for calibration solver to work?

### ISSUE THREAD

**Issue by brinij** [ros-planning/moveit_calibration#40]
Hi,
have you ever tried to calibrate a robot that has less than 6DOF with one of those three solvers that this package is using?
If yes, which one is the best for such a problem?
I have a robot with 4DOF where pitch and yaw are missing.
Thank you in advance!

**Comment by JStech** [comment]
You need at least 2 rotation axes for the solution to be unique, so 3 DoF translation and 1 DoF rotation won't work. There's a proof of this in the [Tsai & Lenz paper](https://pdfs.semanticscholar.org/19b3/89a797a55c8b63dca8b6d1889df4cff8bfaa.pdf), which I haven't read carefully, I admit. Here's how I understand it (although I could be wrong).
 - Translations are only useful for recovering the rotation between the eef and the camera: if I translate the eef in +X, and the camera's motion is in +Z, that tells me that the +X in the eef frame is +Z in the optical frame, but there's no constraint on the translation from the eef frame to the optical frame.
 - Rotating around an axis cannot resolve the translation from the eef frame to the camera frame along that axis: if the eef rotates around the Y axis, the camera's motion will make a circle that must be centered on the Y axis, but could be anywhere in the Y direction.

So, with a single rotation axis, you can't find the translation between the camera and eef along that axis.

I don't know of any published or open source work on partial solvers, but if you find (or come up with) something, you could probably use MoveIt Calibration to collect and export a dataset.
