### ISSUE TITLE
Failed to load calibration plugin with rViz on kinetic version , ubuntu 16.04

### ISSUE THREAD

**Issue by ScottYang1982** [ros-planning/moveit_calibration#42]
![Screenshot from 2020-11-14 04-37-49](https://user-images.githubusercontent.com/22881565/99147277-9cb7dd00-26ba-11eb-8346-3bb51d894920.png)

![Screenshot from 2020-11-14 04-37-49](https://user-images.githubusercontent.com/22881565/99147282-afcaad00-26ba-11eb-8bf9-0b3e2fe6db8d.png)

**Comment by felixvd** [comment]
Duplicate of #9

**Comment by JStech** [comment]
Also, #23. I haven't heard of anyone getting MoveIt Cal to run on kinetic.
