### ISSUE TITLE
Confused about which sensor frame to select

### ISSUE THREAD

**Issue by Victorlouisdg** [ros-planning/moveit_calibration#44]
Hi

I'm trying to do eye-to-hand calibration with a between a Baxter robot and a Kinect2 camera. However I can't figure out which frame I need to select as `Sensor frame:` in the `Context` tab. 

In [this tutorial](https://github.com/JStech/moveit_tutorials/blob/new-calibration-tutorial/doc/hand_eye_calibration/hand_eye_calibration_tutorial.rst) the frame `camera_color_optical_frame` is selected. Is this a frame created by the calibration plugin itself? I've found a similar frame in my tf_tree called `kinect2_rgb_optical_frame`, but I can't select that as sensor frame. I think this might be because it doesn't have "camera" in its name, which seems to be required according to [this comment](https://github.com/ros-planning/moveit/issues/1070#issuecomment-514142891). 
![kinect2_rgb_optical_frame](https://user-images.githubusercontent.com/23340946/99520195-1984d880-2993-11eb-81c5-5460ef7af14c.png)

**Comment by Victorlouisdg** [comment]
I tried removing the [if statement that filters the cameras](https://github.com/ros-planning/moveit_calibration/blob/541e7bb8ca1cfe3500c70df8bd2464f0d481521f/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp#L65) in `handeye_context_widget.cpp`. Then if I select the `kinect2_rgb_optical_frame` as `Sensor frame:` everything seems to work and I can complete the calibration :) 

An easy fix could be to not only include the frames with `camera` in their names, but also the frames with `optical`.

**Comment by samarth-robo** [comment]
That is a good point @Victorlouisdg . Most camera drivers include `optical` in the `frame_id` of the image topic, so it makes sense to check for that rather than `camera`. But more ideally, we should just get the sensor `frame_id` automatically from the image message header.

**Comment by JStech** [comment]
I've run into this myself, although apparently I just made a local branch to work around it and never said anything (sorry). I agree with @samarth-robo that taking the sensor frame directly from the Image or CameraInfo topic makes the most sense.
