### ISSUE TITLE
Crash in calibration after image topic is selected

### ISSUE THREAD

**Issue by vixtor-qm** [ros-planning/moveit_calibration#48]
Hello.

I'm trying to calibrate my realsense and UR3 setup using this toolkit.
I have ROS Melodic and Ubuntu 18.04
OpenCV version is 3.4

I have installed UR_ROBOT_DRIVER and compiled the calibration toolbox.
When I run rviz I see the plugin GUI but it crashes once I pick the camera topic from the drop list.
It gives me this error.
```
[ERROR] [1606993910.391483979]: Invalid target measured dimensions: marker_size 0,000000, marker_seperation 0,000000
```

I definitely set the numbers in the GUI but for some reason the backend is not aware of them

Does anybody else experience this?

**Comment by JStech** [comment]
This looks like #43

**Comment by vixtor-qm** [comment]
yes, it is quite similar. I'll check then. Thanks

**Comment by vixtor-qm** [comment]
Checked and it worked. Thanks for the support
