### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by BunnyIcon** [ros-planning/moveit_calibration#50]
Thanks for your repo. I'm a beginner of ROS, when I use catkin_make, it has errors. That confused me.
Anyone could help me with that? Thanks in advance!!

nvidia@miivii-tegra:~/brickbot_ws$ catkin build
bash: catkin: cannot find command
nvidia@miivii-tegra:~/brickbot_ws$ catkin_make
Base path: /home/nvidia/brickbot_ws
Source space: /home/nvidia/brickbot_ws/src
Build space: /home/nvidia/brickbot_ws/build
Devel space: /home/nvidia/brickbot_ws/devel
Install space: /home/nvidia/brickbot_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/nvidia/brickbot_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/nvidia/brickbot_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/nvidia/brickbot_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/nvidia/brickbot_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 23 packages in topological order:
-- ~~  - brickbot_moveit_config
-- ~~  - robot_control
-- ~~  - ros_numpy
-- ~~  - depth_for_brickbot
-- ~~  - moveit_calibration_plugins
-- ~~  - brickbot_description
-- ~~  - moveit_calibration_gui
-- ~~  - zed_ar_track_alvar_example
-- ~~  - zed_depth_sub_tutorial
-- ~~  - zed_display_rviz
-- ~~  - zed_examples (metapackage)
-- ~~  - zed_interfaces
-- ~~  - zed_multicamera_example
-- ~~  - zed_nodelet_example
-- ~~  - zed_nodelets
-- ~~  - zed_obj_det_sub_tutorial
-- ~~  - zed_ros (metapackage)
-- ~~  - zed_rtabmap_example
-- ~~  - zed_sensors_sub_tutorial
-- ~~  - zed_sync_test
-- ~~  - zed_tracking_sub_tutorial
-- ~~  - zed_video_sub_tutorial
-- ~~  - zed_wrapper
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'brickbot_moveit_config'
-- ==> add_subdirectory(brickbot_moveit_config)
-- +++ processing catkin package: 'robot_control'
-- ==> add_subdirectory(robot_control)
-- +++ processing catkin package: 'ros_numpy'
-- ==> add_subdirectory(ros_numpy)
-- +++ processing catkin package: 'depth_for_brickbot'
-- ==> add_subdirectory(zed-ros-wrapper/depth_for_brickbot)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- depth_for_brickbot: 1 messages, 0 services
-- +++ processing catkin package: 'moveit_calibration_plugins'
-- ==> add_subdirectory(moveit_calibration/moveit_calibration_plugins)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenCV: /usr (found version "3.2.0") found components:  aruco 
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2.7") 
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found suitable version "1.13.3", minimum required is "1.7") 
-- NumPy ver. 1.13.3 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- +++ processing catkin package: 'brickbot_description'
-- ==> add_subdirectory(brickbot_description)
-- +++ processing catkin package: 'moveit_calibration_gui'
-- ==> add_subdirectory(moveit_calibration/moveit_calibration_gui)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenCV: /usr (found version "3.2.0") 
-- +++ processing catkin package: 'zed_ar_track_alvar_example'
-- ==> add_subdirectory(zed-ros-examples/examples/zed_ar_track_alvar_example)
-- +++ processing catkin package: 'zed_depth_sub_tutorial'
-- ==> add_subdirectory(zed-ros-examples/tutorials/zed_depth_sub_tutorial)
-- +++ processing catkin package: 'zed_display_rviz'
-- ==> add_subdirectory(zed-ros-examples/zed_display_rviz)
-- +++ processing catkin metapackage: 'zed_examples'
-- ==> add_subdirectory(zed-ros-examples/zed_examples)
-- +++ processing catkin package: 'zed_interfaces'
-- ==> add_subdirectory(zed-ros-wrapper/zed_interfaces)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- zed_interfaces: 3 messages, 13 services
-- +++ processing catkin package: 'zed_multicamera_example'
-- ==> add_subdirectory(zed-ros-examples/examples/zed_multicamera_example)
-- +++ processing catkin package: 'zed_nodelet_example'
-- ==> add_subdirectory(zed-ros-examples/examples/zed_nodelet_example)
-- +++ processing catkin package: 'zed_nodelets'
-- ==> add_subdirectory(zed-ros-wrapper/zed_nodelets)
-- A library with BLAS API found.
-- Found CUDA: /usr/local/cuda-10.0 (found suitable version "10.0", minimum required is "10") 
-- Found TensorRT (found version "5.1")

-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'zed_obj_det_sub_tutorial'
-- ==> add_subdirectory(zed-ros-examples/tutorials/zed_obj_det_sub_tutorial)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin metapackage: 'zed_ros'
-- ==> add_subdirectory(zed-ros-wrapper/zed_ros)
-- +++ processing catkin package: 'zed_rtabmap_example'
-- ==> add_subdirectory(zed-ros-examples/examples/zed_rtabmap_example)
-- +++ processing catkin package: 'zed_sensors_sub_tutorial'
-- ==> add_subdirectory(zed-ros-examples/tutorials/zed_sensors_sub_tutorial)
-- +++ processing catkin package: 'zed_sync_test'
-- ==> add_subdirectory(zed-ros-examples/tests/zed_sync_test)
-- +++ processing catkin package: 'zed_tracking_sub_tutorial'
-- ==> add_subdirectory(zed-ros-examples/tutorials/zed_tracking_sub_tutorial)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'zed_video_sub_tutorial'
-- ==> add_subdirectory(zed-ros-examples/tutorials/zed_video_sub_tutorial)
-- +++ processing catkin package: 'zed_wrapper'
-- ==> add_subdirectory(zed-ros-wrapper/zed_wrapper)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/brickbot_ws/build
####
####
Scanning dependencies of target moveit_handeye_calibration_solver_core
Scanning dependencies of target moveit_handeye_calibration_target_core
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target brickbot_description_xacro_generated_to_devel_space_
[  0%] Built target _depth_for_brickbot_generate_messages_check_deps_brickbot_msg
[  2%] Built target zed_depth_sub
[  2%] Built target geometry_msgs_generate_messages_eus
[  2%] Built target _zed_interfaces_generate_messages_check_deps_stop_3d_mapping
[  2%] Built target _zed_interfaces_generate_messages_check_deps_stop_remote_stream
[  2%] Built target _zed_interfaces_generate_messages_check_deps_set_pose
[  2%] Built target _zed_interfaces_generate_messages_check_deps_RGBDSensors
[  2%] Built target _zed_interfaces_generate_messages_check_deps_start_object_detection
[  2%] Built target _zed_interfaces_generate_messages_check_deps_reset_tracking
[  3%] Building CXX object moveit_calibration/moveit_calibration_plugins/handeye_calibration_solver/CMakeFiles/moveit_handeye_calibration_solver_core.dir/src/handeye_solver_default.cpp.o
[  4%] Building CXX object moveit_calibration/moveit_calibration_plugins/handeye_calibration_target/CMakeFiles/moveit_handeye_calibration_target_core.dir/src/handeye_target_aruco.cpp.o
[  4%] Built target _zed_interfaces_generate_messages_check_deps_stop_object_detection
[  4%] Building CXX object moveit_calibration/moveit_calibration_plugins/handeye_calibration_target/CMakeFiles/moveit_handeye_calibration_target_core.dir/src/handeye_target_charuco.cpp.o
[  4%] Built target _zed_interfaces_generate_messages_check_deps_start_svo_recording
[  4%] Built target _zed_interfaces_generate_messages_check_deps_stop_svo_recording
[  4%] Built target _zed_interfaces_generate_messages_check_deps_start_remote_stream
[  4%] Built target _zed_interfaces_generate_messages_check_deps_reset_odometry
[  4%] Built target _zed_interfaces_generate_messages_check_deps_ObjectStamped
[  4%] Built target sensor_msgs_generate_messages_lisp
[  4%] Built target _zed_interfaces_generate_messages_check_deps_toggle_led
[  4%] Built target geometry_msgs_generate_messages_lisp
[  4%] Built target _zed_interfaces_generate_messages_check_deps_set_led_status
[  4%] Built target _zed_interfaces_generate_messages_check_deps_Objects
[  4%] Built target _zed_interfaces_generate_messages_check_deps_start_3d_mapping
[  4%] Built target sensor_msgs_generate_messages_cpp
[  4%] Built target geometry_msgs_generate_messages_cpp
[  4%] Built target geometry_msgs_generate_messages_nodejs
[  4%] Built target geometry_msgs_generate_messages_py
[  4%] Built target sensor_msgs_generate_messages_py
[  4%] Built target sensor_msgs_generate_messages_nodejs
[  5%] Built target zed_nodelets_gencfg
[  5%] Built target bond_generate_messages_nodejs
[  5%] Built target rosgraph_msgs_generate_messages_py
[  5%] Built target rosgraph_msgs_generate_messages_nodejs
[  5%] Built target rosgraph_msgs_generate_messages_lisp
[  5%] Built target rosgraph_msgs_generate_messages_cpp
[  5%] Built target rosgraph_msgs_generate_messages_eus
[  5%] Built target roscpp_generate_messages_lisp
[  5%] Built target roscpp_generate_messages_py
Scanning dependencies of target tf2_msgs_generate_messages_py
Scanning dependencies of target actionlib_msgs_generate_messages_cpp
[  5%] Built target roscpp_generate_messages_nodejs
[  5%] Built target roscpp_generate_messages_eus
[  5%] Built target tf2_msgs_generate_messages_py
[  5%] Built target roscpp_generate_messages_cpp
Scanning dependencies of target tf2_msgs_generate_messages_nodejs
[  5%] Built target actionlib_msgs_generate_messages_cpp
Scanning dependencies of target tf2_msgs_generate_messages_eus
Scanning dependencies of target actionlib_generate_messages_nodejs
Scanning dependencies of target tf2_msgs_generate_messages_lisp
[  5%] Built target tf2_msgs_generate_messages_nodejs
[  5%] Built target tf2_msgs_generate_messages_eus
Scanning dependencies of target actionlib_generate_messages_py
[  5%] Built target actionlib_generate_messages_nodejs
[  5%] Built target tf2_msgs_generate_messages_lisp
Scanning dependencies of target tf2_msgs_generate_messages_cpp
Scanning dependencies of target actionlib_msgs_generate_messages_eus
[  5%] Built target actionlib_generate_messages_py
Scanning dependencies of target actionlib_msgs_generate_messages_lisp
[  5%] Built target tf2_msgs_generate_messages_cpp
[  5%] Built target actionlib_msgs_generate_messages_eus
Scanning dependencies of target actionlib_msgs_generate_messages_nodejs
Scanning dependencies of target actionlib_generate_messages_lisp
[  5%] Built target actionlib_msgs_generate_messages_lisp
Scanning dependencies of target actionlib_msgs_generate_messages_py
Scanning dependencies of target actionlib_generate_messages_cpp
[  5%] Built target actionlib_generate_messages_lisp
[  5%] Built target actionlib_msgs_generate_messages_nodejs
Scanning dependencies of target actionlib_generate_messages_eus
[  5%] Built target actionlib_msgs_generate_messages_py
[  5%] Built target actionlib_generate_messages_cpp
Scanning dependencies of target dynamic_reconfigure_generate_messages_lisp
Scanning dependencies of target dynamic_reconfigure_gencfg
[  5%] Built target actionlib_generate_messages_eus
Scanning dependencies of target dynamic_reconfigure_generate_messages_py
[  5%] Built target dynamic_reconfigure_gencfg
[  5%] Built target dynamic_reconfigure_generate_messages_lisp
Scanning dependencies of target dynamic_reconfigure_generate_messages_eus
[  5%] Built target dynamic_reconfigure_generate_messages_py
Scanning dependencies of target dynamic_reconfigure_generate_messages_cpp
Scanning dependencies of target dynamic_reconfigure_generate_messages_nodejs
[  5%] Built target dynamic_reconfigure_generate_messages_eus
[  5%] Built target dynamic_reconfigure_generate_messages_cpp
[  5%] Built target diagnostic_msgs_generate_messages_py
[  5%] Built target dynamic_reconfigure_generate_messages_nodejs
[  5%] Built target stereo_msgs_generate_messages_nodejs
[  5%] Built target diagnostic_msgs_generate_messages_lisp
[  5%] Built target nodelet_generate_messages_nodejs
[  5%] Built target nodelet_generate_messages_cpp
[  5%] Built target stereo_msgs_generate_messages_cpp
[  5%] Built target stereo_msgs_generate_messages_py
[  5%] Built target nodelet_generate_messages_eus
[  5%] Built target bond_generate_messages_eus
[  5%] Built target diagnostic_msgs_generate_messages_eus
[  5%] Built target bond_generate_messages_py
[  5%] Built target stereo_msgs_generate_messages_eus
[  5%] Built target diagnostic_msgs_generate_messages_cpp
[  5%] Built target nodelet_generate_messages_lisp
[  5%] Built target bond_generate_messages_cpp
[  5%] Built target bond_generate_messages_lisp
[  5%] Built target diagnostic_msgs_generate_messages_nodejs
[  5%] Built target stereo_msgs_generate_messages_lisp
[  5%] Built target nodelet_generate_messages_py
[  6%] Built target depth_for_brickbot_generate_messages_nodejs
[  7%] Built target zed_sensors_sub
[ 10%] Built target zed_tracking_sub
[ 11%] Built target zed_video_sub
[ 12%] Built target depth_for_brickbot_generate_messages_cpp
[ 13%] Built target depth_for_brickbot_generate_messages_py
[ 14%] Built target depth_for_brickbot_generate_messages_lisp
[ 15%] Built target depth_for_brickbot_generate_messages_eus
[ 29%] Built target zed_interfaces_generate_messages_eus
[ 42%] Built target zed_interfaces_generate_messages_lisp
[ 53%] Built target zed_interfaces_generate_messages_cpp
[ 67%] Built target zed_interfaces_generate_messages_py
[ 79%] Built target zed_interfaces_generate_messages_nodejs
[ 79%] Built target depth_for_brickbot_generate_messages
[ 81%] Built target zed_wrapper_node
[ 82%] Built target ZEDSyncTest
[ 82%] Built target zed_interfaces_generate_messages
[ 84%] Built target zed_obj_det_sub
[ 87%] Built target ZEDNodelets
[ 88%] Linking CXX shared library /home/nvidia/brickbot_ws/devel/lib/libmoveit_handeye_calibration_solver_core.so
[ 88%] Built target moveit_handeye_calibration_solver_core
Scanning dependencies of target moveit_handeye_calibration_solver
[ 89%] Building CXX object moveit_calibration/moveit_calibration_plugins/handeye_calibration_solver/CMakeFiles/moveit_handeye_calibration_solver.dir/src/plugin_init.cpp.o
[ 90%] Linking CXX shared library /home/nvidia/brickbot_ws/devel/lib/libmoveit_handeye_calibration_target_core.so
[ 90%] Built target moveit_handeye_calibration_target_core
Scanning dependencies of target moveit_handeye_calibration_target
[ 90%] Building CXX object moveit_calibration/moveit_calibration_plugins/handeye_calibration_target/CMakeFiles/moveit_handeye_calibration_target.dir/src/plugin_init.cpp.o
[ 90%] Linking CXX shared library /home/nvidia/brickbot_ws/devel/lib/libmoveit_handeye_calibration_solver.so
[ 90%] Built target moveit_handeye_calibration_solver
[ 92%] Linking CXX shared library /home/nvidia/brickbot_ws/devel/lib/libmoveit_handeye_calibration_target.so
[ 92%] Built target moveit_handeye_calibration_target
Scanning dependencies of target moveit_handeye_calibration_rviz_plugin_core_autogen
[ 93%] Automatic MOC for target moveit_handeye_calibration_rviz_plugin_core
[ 93%] Built target moveit_handeye_calibration_rviz_plugin_core_autogen
Scanning dependencies of target moveit_handeye_calibration_rviz_plugin_core
[ 94%] Building CXX object moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_calibration_gui.cpp.o
[ 95%] Building CXX object moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_target_widget.cpp.o
[ 95%] Building CXX object moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_context_widget.cpp.o
[ 96%] Building CXX object moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_control_widget.cpp.o
[ 97%] Building CXX object moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/moveit_handeye_calibration_rviz_plugin_core_autogen/mocs_compilation.cpp.o
/home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp: In member function ‘void moveit_rviz_plugin::ContextTabWidget::updateAllMarkers()’:
/home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp:327:16: error: ‘class rviz_visual_tools::TFVisualTools’ has no member named ‘clearAllTransforms’; did you mean ‘publishAllTransforms’?
     tf_tools_->clearAllTransforms();
                ^~~~~~~~~~~~~~~~~~
                publishAllTransforms
/home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp:376:81: error: no matching function for call to ‘moveit_visual_tools::MoveItVisualTools::publishMesh(Eigen::Isometry3d&, shape_msgs::Mesh&, rviz_visual_tools::colors, double, const char [4], int)’
           visual_tools_->publishMesh(fov_pose_, mesh, rvt::YELLOW, 1.0, "fov", 1);
                                                                                 ^
In file included from /home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_context_widget.h:58:0,
                 from /home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp:37:
/opt/ros/melodic/include/rviz_visual_tools/rviz_visual_tools.h:829:8: note: candidate: bool rviz_visual_tools::RvizVisualTools::publishMesh(const Isometry3d&, const string&, rviz_visual_tools::colors, double, const string&, std::size_t)
   bool publishMesh(const Eigen::Isometry3d& pose, const std::string& file_name, colors color = CLEAR, double scale = 1,
        ^~~~~~~~~~~
/opt/ros/melodic/include/rviz_visual_tools/rviz_visual_tools.h:829:8: note:   no known conversion for argument 2 from ‘shape_msgs::Mesh {aka shape_msgs::Mesh_<std::allocator<void> >}’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
/opt/ros/melodic/include/rviz_visual_tools/rviz_visual_tools.h:831:8: note: candidate: bool rviz_visual_tools::RvizVisualTools::publishMesh(const Pose&, const string&, rviz_visual_tools::colors, double, const string&, std::size_t)
   bool publishMesh(const geometry_msgs::Pose& pose, const std::string& file_name, colors color = CLEAR,
        ^~~~~~~~~~~
/opt/ros/melodic/include/rviz_visual_tools/rviz_visual_tools.h:831:8: note:   no known conversion for argument 1 from ‘Eigen::Isometry3d {aka Eigen::Transform<double, 3, 1>}’ to ‘const Pose& {aka const geometry_msgs::Pose_<std::allocator<void> >&}’
/home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp: In member function ‘bool moveit_rviz_plugin::ControlTabWidget::solveCameraRobotPose()’:
/home/nvidia/brickbot_ws/src/moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp:399:20: error: ‘class rviz_visual_tools::TFVisualTools’ has no member named ‘clearAllTransforms’; did you mean ‘publishAllTransforms’?
         tf_tools_->clearAllTransforms();
                    ^~~~~~~~~~~~~~~~~~
                    publishAllTransforms
moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/build.make:110: recipe for target 'moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_context_widget.cpp.o' failed
make[2]: *** [moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_context_widget.cpp.o] Error 1
make[2]: *** Waiting for unfinished tasks....
moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/build.make:134: recipe for target 'moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_control_widget.cpp.o' failed
make[2]: *** [moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/src/handeye_control_widget.cpp.o] Error 1
CMakeFiles/Makefile2:5551: recipe for target 'moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/all' failed
make[1]: *** [moveit_calibration/moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeFiles/moveit_handeye_calibration_rviz_plugin_core.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by JStech** [comment]
Check out #23, I think that might be what you're running into.
