### ISSUE TITLE
Small bug encountered when using automatic calibration

### ISSUE THREAD

**Issue by FrankLin9981** [ros-planning/moveit_calibration#54]
Hi all,

I find a bug when I use automatic calibration to execute the recorded joint states.
After the execution of the plan is done, it will not automatically take a sample.

I trace source codes of the GUI and find that it results from the if statement as shown in the figure below.
If execution succeeds, variable **planning_res_** will be equal to **ControlTabWidget::SUCCESS**, which is equal to 0.
The if statement `if (planning_res_)` which includes the function to take sample will not be entered.
I solve it by changing the statement into `if (planning_res_ == ControlTabWidget::SUCCESS)`.

![image](https://user-images.githubusercontent.com/39838168/103075279-3baeed80-4606-11eb-9ce3-9db2ad60bf0b.png)
![image](https://user-images.githubusercontent.com/39838168/103075414-829ce300-4606-11eb-9e99-5eb7edc03a83.png)

Sincerely,

Frank

**Comment by JStech** [comment]
Thank you for finding and fixing this! If you'd like to open a PR with your fix, I'll happily merge it. If you'd rather not, I can do it.

**Comment by FrankLin9981** [comment]
@JStech 
Thank you for helping me open a PR!
