### ISSUE TITLE
Failed to load python module: handeye.calibrator

### ISSUE THREAD

**Issue by GeorgeNegret** [ros-planning/moveit_calibration#55]
Hi,
when I try to take the fifth sample I get this error : 
" [ERROR] : Failed to load python module: handeye.calibrator
ImportError: No module named handeye.calibrator "
![Screenshot from 2020-12-30 16-02-08](https://user-images.githubusercontent.com/44939472/103356613-eec19000-4ab9-11eb-93d9-bef2ae64b4d7.png)

**Comment by GeorgeNegret** [comment]
Solved ! 
after I cloned :[](url)https://github.com/crigroup/criutils , [https://github.com/crigroup/baldor](url) , [https://github.com/crigroup/handeye](url) in my workspace

**Comment by Roycel** [comment]
Hello, i get the same error now. i try to install https://github.com/crigroup/criutils and https://github.com/crigroup/baldor into my catkin workspace, but the error is still there.
why need this two packages ? :joy: 
my ROS distro is melodic @GeorgeNegret

**Comment by JStech** [comment]
These packages are needed because they provide the actual solver implementations used in MoveIt Calibration. They can be installed with [rosdep](http://wiki.ros.org/rosdep#Install_dependency_of_all_packages_in_the_workspace) or manually with `sudo apt install ros-melodic-handeye ros-melodic baldor`.

**Comment by Roycel** [comment]
nice! I have solved my errors after I installed [handeye](https://github.com/crigroup/handeye) , [criutils](https://github.com/crigroup/criutils) , [baldor](https://github.com/crigroup/baldor) , scipy.  Thank you very much ! :thumbsup:

**Comment by LiJihao138** [comment]
I have installed criutils,baldor.    How can i install handeye
