### ISSUE TITLE
Camera intrinsics not read correctly from the ros topic (unsupported distortion models)

### ISSUE THREAD

**Issue by tejaswid** [ros-planning/moveit_calibration#77]
Ubuntu 18.04, OpenCV 3.2, ROS Melodic.

I was trying to use this plugin to perform hand eye calibration for a Realsense D435 mounted on a UR5e arm, all in simulation in Gazebo 9.0. My calibration pattern was a ChArUco board.

While the markers were correctly detected, I noticed that the interpolated corners and the pose of the board with respect to the camera was always off. This obviously resulted in very bad calibration results. I noticed that when I implemented a Charuco board detection independent of this plugin (using ([reference](https://docs.opencv.org/master/df/d4a/tutorial_charuco_detection.html))) the pose of the board was being computed correctly.

See the figure below. Left - from this plugin, Right - independent implementation of the exact same ChArUco code .
![image](https://user-images.githubusercontent.com/11408325/112487506-df0fca00-8dd0-11eb-9f4f-5adba04f3ba1.png)

Digging further, I noticed that when I printed the `camera_martrix_` from inside `handeye_target_charuco.cpp`, it was always identity (the value it is initialized to), but the echoing the rostopic actually had the correct values.

**Comment by JStech** [comment]
Thanks for the report--could be a real issue. Can you reproduce this? Can you double-check that you have the right topic selected in the "CameraInfo Topic" dropdown on the Target tab?

**Comment by tejaswid** [comment]
I am confident that I am selecting the correct CameraInfo Topic but I can double check and report back. Will get back to you in a day. If it makes sense, i will share my simulation environment as well. Should help with your efforts on the simulation front as well.

**Comment by JStech** [comment]
Thanks for sharing the sim--that was the next thing I was gonna ask. I'll take a look this weekend (probably).

**Comment by tejaswid** [comment]
Got to the bottom of this. The camera intrinsics were not being set because the ROS camera_info topic had an empty distortion matrix. So the `cameraInfoCallback` function ([here](https://github.com/ros-planning/moveit_calibration/blob/master/moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_target_widget.cpp#L439)) was not updating the intrinsics.

The bug is **not in this package** but in the [realsense_gazebo_plugin](https://github.com/pal-robotics/realsense_gazebo_plugin) that I was using to simulate a Realsense camera in gazebo. Specifically in [this function](https://github.com/pal-robotics/realsense_gazebo_plugin/blob/melodic-devel/src/gazebo_ros_realsense.cpp#L249), the distortion values is not set causing `msg->D` in the input to `cameraInfoCallback` to be an empty vector.

I am closing this issue as resolved.

**Comment by JStech** [comment]
Sounds good. MoveIt Calibration could handle an empty distortion vector--just treat it as all zeros. I'll leave this closed, but I might create a feature request for that.

**Comment by JStech** [comment]
Another user just ran into a similar problem--they have a camera node publishing a `rational_polynomial` distortion model, with 8 parameters, which is also getting silently dropped (although further down in the code).

I'm reopening this issue. I think MoveIt Calibration should be able to handle the rational polynomial distortion model, and no distortion model, and it should fail more obviously when it does fail.

**Comment by foreverbala** [comment]
@tejaswid 

I am using logitech C270 as webcam and doing eye-to-hand calibration. I am also facing the same issue you mentioned here. I am also getting that blue line from the corner of the image tab as you shown in the left image. This gives me the bad results. Could you please tell me how do you solve this issue?
Thanks in advance.

**Comment by tejaswid** [comment]
@foreverbala My issue was due to another package not correctly setting the distortion parameters of the intrinsics matrix. Please double check if the intrinsics are being correctly set.

**Comment by foreverbala** [comment]
@tejaswid 
Thanks for your reply. Could you please tell me, where I want to check that if my intrinsics are set correctly during hand eye calibration?

Thanks in advance

**Comment by foreverbala** [comment]
@tejaswid 
I have cleared the issue by setting the cameras intrinsic parameters in the camera_info.yaml file.
Thanks for your time

**Comment by yulan0215** [comment]
Hi, I have a question that how did you generate the Charuco marker board in the gazebo? Thx

**Comment by praj441** [comment]
> [@tejaswid](https://github.com/tejaswid) I have cleared the issue by setting the cameras intrinsic parameters in the camera_info.yaml file. Thanks for your time

@tejaswid 
Where to find the file camera_info.yaml and how to set the intrinsic parameters in it?
